networks:
  app_network:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app_network

  django1:
    build:
      context: .
    container_name: django1
    volumes:
      - .:/app/
    depends_on:
      - redis
    expose:
      - '8000'
    networks:
      - app_network
    env_file:
      - .env

  django2:
    build:
      context: .
    container_name: django2
    volumes:
      - .:/app/
    depends_on:
      - redis
    expose:
      - '8000'
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django1
      - django2
    networks:
      - app_network

  ab:  # will fail
    image: jordi/ab
    container_name: ab
    depends_on:
      - nginx
    networks:
      - app_network
  # docker compose run ab bash
    # ab -n 1000 -c 10 http://nginx/
