events {}

http {
    upstream django_servers {
        server django1:8000;
        server django2:8000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://django_servers;
        }
    }
}
